---
title: "Final Project"
subtitle: ""
author: "Rohan Anand, Coby Wilcox"
date: last-modified
published-title: "Updated"
editor: visual
format: html
code-copy: true
execute:
  message: false
  warning: false
  echo: false
  cache: true
---

```{r}
library(ggplot2)
library(corrplot)
library(reshape2)
library(ggcorrplot)
library(tidyverse)
library(ISLR)
library(glmnet)
library(tree)
library(maptree)
library(randomForest)
library(gbm)
library(ROCR)
library(dplyr)
```

## Abstract

This report investigates the predictive power of various economic indicators, including S&P500 data, Treasury Bond yields, unemployment rate, real personal income, industrial production, real GDP, and more, to develop a machine learning model for forecasting economic recessions within the next 12 months. The employed machine learning methods encompass logistic regression, ridge and lasso regression, random forests with and without boosting for ensemble-based learning, and neural networks, which capture complex relationships within the data. Inspired by contemporary economic trends, this analysis aims to employ machine learning techniques to enhance recession prediction accuracy and serve as a starting point to contribute valuable insights for informed decision-making.

## Dataset

This dataset encompasses a diverse array of critical economic indicators, providing a comprehensive view of the U.S. economic landscape. The dataset includes key metrics for the following from 1982 to 2023, updated in monthly intervals:

+--------------------------------------------+----------------------------------+
| \- **Consumer Price Index (CPI)**          | \- S&P 500 returns               |
+============================================+==================================+
| \- 10-year & 3-month treasury bond yields  | \- National unemployment rate    |
+--------------------------------------------+----------------------------------+
| -   Real personal income                   | \- Number of U.S. workers        |
+--------------------------------------------+----------------------------------+
| -   Industrial Production                  | \- Real retail sales             |
+--------------------------------------------+----------------------------------+
| -   AAA/BAA yield curve of corporate bonds | \- Heavy Truck Sales             |
+--------------------------------------------+----------------------------------+

-   10-year and 3-month treasury bond yield rates

-   National unemployment rate

-   Real personal income

-   Number of U.S. workers

-   Industrial Production

-   Real retail sales

-   AAA/BAA yield curve of corporate bonds

-   Heavy Truck Sales

-   Consumer Price Index (CPI)

-   S&P 500 returns

-   real GDP

    Within this context, the government typically defines a recession as a sustained period of economic decline marked by a contraction in real GDP for two consecutive quarters. This widely accepted definition captures the essence of a recession, reflecting reduced economic activity, rising unemployment, and potential impacts on various sectors, all of which are crucial factors monitored within this dataset to better understand and predict economic cycles.

For the purposes of this analysis, we have explicity

## Methodology

```{mermaid}
flowchart LR
  A[Preprocessed Data] --> B(Evaluate Outliers)
  B --> C{Log_transformation}
  C --> D[Multiple Testing]
  C --> E[Random Forests]
  D --> F[Fuzzy Transformation]
  E --> F
  F --> G[Logistic Regression]
```

Diagram of the workflow for the methodologies that we will explore in our analysis.

## Results 

## Further Considerations

Mention Time Series Analysis
